name: Linux
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master

    - name: Build 32-bit
      run: zig build test -Dtarget=i386-linux-gnu --prefix tmp

    - name: Build 64-bit
      run: |
        zig build test --prefix zig-out
        echo $GITHUB_ACTION_PATH/zig-out/bin/gyro >> $GITHUB_PATH

    - name: Fetch a test gyro.zzz file
      run: gyro fetch
      working-directory: tests
