name: Linux
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master

    - name: Build 32-bit
      run: zig build test -Dtarget=x86-linux-musl --prefix tmp

    - name: Build 64-bit
      run: zig build

    - name: Test
      run: zig build test -Dtarget=x86_64-linux-musl

    - name: Fetch a test gyro.zzz file
      run: ../zig-out/bin/gyro fetch
      working-directory: tests

    - name: Update test
      run: ../zig-out/bin/gyro update upaya
      working-directory: tests
