name: Linux
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master

    - name: Bootstrap build
      run: zig build test -Dbootstrap --prefix zig-out

    - name: Bootstrap build 32-bit
      run: zig build test -Dbootstrap -Dtarget=i386-linux-gnu --prefix tmp
